# Generated by Django 5.2.4 on 2025-07-27 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid barcode number (8 to 13 digits).', regex='^\\d{8,13}$')]),
        ),
    ]
