# Generated by Django 5.2.4 on 2025-07-15 09:08

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.barcode_image_upload_path),
        ),
    ]
