# Generated by Django 5.2.4 on 2025-07-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode_image',
        ),
    ]
