# Generated by Django 5.2.4 on 2025-07-29 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_unique_id_purchase_purchaseitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15),
        ),
        migrations.CreateModel(
            name='PurchaseItemLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.location')),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_locations', to='products.purchaseitem')),
            ],
            options={
                'unique_together': {('purchase_item', 'location')},
            },
        ),
    ]
