# Generated by Django 5.2.4 on 2025-07-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_purchaseitem_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15, null=True),
        ),
    ]
