# Generated by Django 5.2.4 on 2025-07-31 07:52

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_purchase_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Card', 'Card'), ('Online', 'Online')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='invoice_image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.invoice_image_upload_path),
        ),
    ]
