# Generated by Django 5.2.4 on 2025-08-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_purchase_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchased_by',
            field=models.CharField(blank=True, choices=[('AZIZIYAH_SHOP', 'AZIZIYAH_SHOP'), ('ALWAB_SHOP', 'ALWAB_SHOP'), ('MAIN_STORE', 'MAIN_STORE'), ('JAMSHEER', 'JAMSHEER'), ('FAWAS', 'FAWAS'), ('IRSHAD', 'IRSHAD'), ('MOOSA', 'MOOSA'), ('FATHIH', 'FATHIH'), ('FIROZ', 'FIROZ')], max_length=20, null=True),
        ),
    ]
