# Generated by Django 5.2.4 on 2025-08-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_purchase_purchased_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
