# Generated by Django 5.2.4 on 2025-08-02 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_purchase_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='minimum_profit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
    ]
