# Generated by Django 5.2.4 on 2025-08-02 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_minimum_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='product_barcode',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='product_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='product_variant',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
