# Generated by Django 5.2.4 on 2025-08-13 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_purchaseitem_product_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Barcode must be 8–30 characters, uppercase letters and digits only.', regex='^[A-Z0-9]{8,30}$')]),
        ),
    ]
