# Generated by Django 5.2.4 on 2025-08-25 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unique_id',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Barcode must be 8–30 characters, letters, digits, and hyphens only.', regex='^[A-Za-z0-9\\-]{8,30}$')]),
        ),
    ]
