# Generated by Django 5.2.4 on 2025-08-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='fulfilled_backorder',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
