# Generated by Django 5.2.4 on 2025-08-29 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_paymentmode_purchasedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.paymentmode'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchased_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.purchasedby'),
        ),
    ]
