# Generated by Django 5.2.4 on 2025-09-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_purchase_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
    ]
