# Generated by Django 5.2.4 on 2025-09-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_purchaseitem_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
    ]
