# Generated by Django 5.2.4 on 2025-08-13 07:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0014_alter_product_unique_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Sales Channel',
                'verbose_name_plural': 'Sales Channels',
            },
        ),
        migrations.CreateModel(
            name='SalesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sales.saleschannel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_sections', to='products.location')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit'), ('Online', 'Online')], max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.saleschannel')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.salessection')),
            ],
            options={
                'ordering': ['-sale_datetime'],
            },
        ),
        migrations.CreateModel(
            name='SectionProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_prices', to='products.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='sales.salessection')),
            ],
        ),
        migrations.AddIndex(
            model_name='salessection',
            index=models.Index(fields=['channel', 'name'], name='sales_sales_channel_cd2499_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salessection',
            unique_together={('channel', 'name')},
        ),
        migrations.AddIndex(
            model_name='sectionproductprice',
            index=models.Index(fields=['section', 'product'], name='sales_secti_section_4e2939_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sectionproductprice',
            unique_together={('section', 'product')},
        ),
    ]
