# Generated by Django 5.2.4 on 2025-08-14 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_unique_id'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('product_brand', models.CharField(blank=True, max_length=100)),
                ('product_variant', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.location')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
        ),
    ]
