# Generated by Django 5.2.4 on 2025-08-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_invoice_number_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessection',
            name='building_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salessection',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='section_logos/'),
        ),
        migrations.AddField(
            model_name='salessection',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salessection',
            name='street_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salessection',
            name='zone_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
