# Generated by Django 5.2.4 on 2025-08-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_customer_salesreturn_salesreturnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='refund_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('wallet', 'Wallet')], default='cash', max_length=10),
        ),
    ]
