# Generated by Django 5.2.4 on 2025-08-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesreturn_refund_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreturn',
            name='refund_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online'), ('wallet', 'Wallet')], default='cash', max_length=10),
        ),
    ]
