# Generated by Django 5.2.4 on 2025-08-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_salesreturn_refund_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionproductprice',
            old_name='price',
            new_name='auto_price',
        ),
        migrations.AddField(
            model_name='sectionproductprice',
            name='manual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
