# Generated by Django 5.2.4 on 2025-08-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_rename_price_sectionproductprice_auto_price_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sectionproductprice',
            name='sales_secti_section_4e2939_idx',
        ),
        migrations.RenameField(
            model_name='sectionproductprice',
            old_name='auto_price',
            new_name='selling_price',
        ),
        migrations.AlterUniqueTogether(
            name='sectionproductprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sectionproductprice',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='sectionproductprice',
            name='manual_price',
        ),
    ]
