# Generated by Django 5.2.4 on 2025-08-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_unique_id'),
        ('sales', '0008_remove_sectionproductprice_sales_secti_section_4e2939_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionproductprice',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='sectionproductprice',
            unique_together={('section', 'product')},
        ),
        migrations.AddIndex(
            model_name='sectionproductprice',
            index=models.Index(fields=['section', 'product'], name='sales_secti_section_4e2939_idx'),
        ),
    ]
