# Generated by Django 5.2.4 on 2025-08-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_sectionproductprice_selling_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessection',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
