# Generated by Django 5.2.4 on 2025-08-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_salessection_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='backorder_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
