# Generated by Django 5.2.4 on 2025-08-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile', models.CharField(db_index=True, max_length=20, unique=True)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
